import type { Movie, Theatre } from './types';

export const movies: Movie[] = [
  {
    id: 1,
    title: 'Shadow Protocol',
    genre: ['Action', 'Thriller'],
    language: ['Hindi', 'English', 'Tamil'],
    duration: 148,
    rating: 8.4,
    votes: 124500,
    releaseDate: '2025-06-20',
    description:
      'A rogue intelligence agent uncovers a global conspiracy that threatens the very fabric of modern civilization. Racing against time, he must navigate a labyrinth of deception, betrayal, and explosive confrontations to expose the truth.',
    cast: [
      { name: 'Arjun Kapoor', role: 'Agent Vikram', image: '' },
      { name: 'Priya Sharma', role: 'Dr. Nisha', image: '' },
      { name: 'Rahul Mehta', role: 'Director Singh', image: '' },
      { name: 'Sanya Malhotra', role: 'Maya', image: '' },
    ],
    director: 'Rohit Shetty',
    image: '/images/movie1.jpg',
    banner: '/images/hero-bg.jpg',
    certificate: 'UA',
    format: ['2D', '3D', 'IMAX'],
  },
  {
    id: 2,
    title: 'Forever & Always',
    genre: ['Romance', 'Drama'],
    language: ['Hindi', 'English'],
    duration: 132,
    rating: 7.8,
    votes: 89200,
    releaseDate: '2025-06-15',
    description:
      'Two strangers meet on a cross-country train journey and discover that love can bloom in the most unexpected places. A heartwarming story about second chances, healing, and the courage to love again.',
    cast: [
      { name: 'Deepika Padukone', role: 'Ananya', image: '' },
      { name: 'Ranbir Kapoor', role: 'Aryan', image: '' },
      { name: 'Tabu', role: 'Mrs. Mehra', image: '' },
      { name: 'Pankaj Tripathi', role: 'Mr. Sharma', image: '' },
    ],
    director: 'Imtiaz Ali',
    image: '/images/movie2.jpg',
    banner: '/images/movie2.jpg',
    certificate: 'U',
    format: ['2D'],
  },
  {
    id: 3,
    title: 'Nebula Rising',
    genre: ['Sci-Fi', 'Adventure'],
    language: ['English', 'Hindi'],
    duration: 162,
    rating: 9.1,
    votes: 215000,
    releaseDate: '2025-06-10',
    description:
      'In 2157, humanity\u2019s last hope lies in a daring mission to a distant galaxy. A crew of unlikely heroes must face impossible odds, alien civilizations, and the dark recesses of space to save Earth from extinction.',
    cast: [
      { name: 'Chris Evans', role: 'Commander Zane', image: '' },
      { name: 'Zendaya', role: 'Dr. Lyra', image: '' },
      { name: 'Idris Elba', role: 'Admiral Cross', image: '' },
      { name: 'Florence Pugh', role: 'Engineer Mara', image: '' },
    ],
    director: 'Denis Villeneuve',
    image: '/images/movie3.jpg',
    banner: '/images/movie3.jpg',
    certificate: 'UA',
    format: ['2D', '3D', 'IMAX', '4DX'],
  },
  {
    id: 4,
    title: 'The Last Witness',
    genre: ['Thriller', 'Mystery'],
    language: ['Hindi', 'English'],
    duration: 138,
    rating: 8.0,
    votes: 67800,
    releaseDate: '2025-06-05',
    description:
      'A forensic investigator stumbles upon a decades-old cold case that connects a series of present-day murders. As she digs deeper, she realizes the killer might be closer than she thinks.',
    cast: [
      { name: 'Vidya Balan', role: 'Inspector Kavya', image: '' },
      { name: 'Manoj Bajpayee', role: 'Commissioner Roy', image: '' },
      { name: 'Nawazuddin Siddiqui', role: 'The Suspect', image: '' },
    ],
    director: 'Sriram Raghavan',
    image: '/images/movie4.jpg',
    banner: '/images/movie4.jpg',
    certificate: 'A',
    format: ['2D'],
  },
  {
    id: 5,
    title: 'Popcorn Chaos',
    genre: ['Comedy', 'Family'],
    language: ['Hindi', 'Telugu', 'Tamil'],
    duration: 118,
    rating: 7.2,
    votes: 45600,
    releaseDate: '2025-05-30',
    description:
      'When a family\u2019s dream vacation goes hilariously wrong, they must band together through a series of outrageous mishaps, unexpected friendships, and laugh-out-loud moments that will warm every heart.',
    cast: [
      { name: 'Akshay Kumar', role: 'Raj', image: '' },
      { name: 'Kiara Advani', role: 'Priya', image: '' },
      { name: 'Varun Dhawan', role: 'Tony', image: '' },
    ],
    director: 'David Dhawan',
    image: '/images/movie5.jpg',
    banner: '/images/movie5.jpg',
    certificate: 'U',
    format: ['2D', '3D'],
  },
  {
    id: 6,
    title: 'Iron Fist 2',
    genre: ['Action', 'Superhero'],
    language: ['English', 'Hindi', 'Tamil', 'Telugu'],
    duration: 155,
    rating: 8.7,
    votes: 312000,
    releaseDate: '2025-05-25',
    description:
      'The Iron Fist returns to face his most dangerous enemy yet — a shadow organization that has infiltrated every government on Earth. With new allies and upgraded powers, the battle for humanity begins.',
    cast: [
      { name: 'Tom Holland', role: 'Iron Fist', image: '' },
      { name: 'Chadwick Boseman', role: 'Shadow King', image: '' },
      { name: 'Scarlett Johansson', role: 'Agent Voss', image: '' },
    ],
    director: 'Russo Brothers',
    image: '/images/movie1.jpg',
    banner: '/images/hero-bg.jpg',
    certificate: 'UA',
    format: ['2D', '3D', 'IMAX', '4DX'],
  },
];

export const theatres: Theatre[] = [
  {
    id: 1,
    name: 'PVR Cinemas - Phoenix Mall',
    location: 'Lower Parel, Mumbai',
    distance: '2.3 km',
    amenities: ['Food Court', 'Parking', 'Wheelchair Access', 'M-Ticket'],
    shows: [
      {
        id: 101,
        time: '09:30 AM',
        format: '2D',
        language: 'Hindi',
        price: { silver: 180, gold: 280, platinum: 450 },
        availableSeats: 45,
        totalSeats: 120,
      },
      {
        id: 102,
        time: '01:00 PM',
        format: '3D',
        language: 'Hindi',
        price: { silver: 220, gold: 320, platinum: 500 },
        availableSeats: 12,
        totalSeats: 120,
      },
      {
        id: 103,
        time: '04:30 PM',
        format: 'IMAX',
        language: 'English',
        price: { silver: 350, gold: 500, platinum: 700 },
        availableSeats: 78,
        totalSeats: 180,
      },
      {
        id: 104,
        time: '08:00 PM',
        format: '2D',
        language: 'Hindi',
        price: { silver: 200, gold: 300, platinum: 480 },
        availableSeats: 3,
        totalSeats: 120,
      },
      {
        id: 105,
        time: '11:00 PM',
        format: '3D',
        language: 'English',
        price: { silver: 220, gold: 320, platinum: 500 },
        availableSeats: 95,
        totalSeats: 120,
      },
    ],
  },
  {
    id: 2,
    name: 'INOX - R-City Mall',
    location: 'Ghatkopar, Mumbai',
    distance: '5.1 km',
    amenities: ['Parking', 'Wheelchair Access', 'M-Ticket', 'Dolby Atmos'],
    shows: [
      {
        id: 201,
        time: '10:00 AM',
        format: '2D',
        language: 'Hindi',
        price: { silver: 160, gold: 250, platinum: 420 },
        availableSeats: 60,
        totalSeats: 100,
      },
      {
        id: 202,
        time: '02:30 PM',
        format: '3D',
        language: 'Tamil',
        price: { silver: 200, gold: 300, platinum: 480 },
        availableSeats: 0,
        totalSeats: 100,
      },
      {
        id: 203,
        time: '06:45 PM',
        format: '2D',
        language: 'English',
        price: { silver: 180, gold: 280, platinum: 450 },
        availableSeats: 35,
        totalSeats: 100,
      },
      {
        id: 204,
        time: '10:15 PM',
        format: '3D',
        language: 'Hindi',
        price: { silver: 200, gold: 300, platinum: 480 },
        availableSeats: 88,
        totalSeats: 100,
      },
    ],
  },
  {
    id: 3,
    name: 'Cinepolis - Viviana Mall',
    location: 'Thane, Mumbai',
    distance: '12.7 km',
    amenities: ['Food Court', 'Parking', 'Recliner Seats', 'M-Ticket'],
    shows: [
      {
        id: 301,
        time: '11:15 AM',
        format: '2D',
        language: 'Hindi',
        price: { silver: 150, gold: 240, platinum: 400 },
        availableSeats: 72,
        totalSeats: 90,
      },
      {
        id: 302,
        time: '03:30 PM',
        format: '4DX',
        language: 'English',
        price: { silver: 400, gold: 550, platinum: 750 },
        availableSeats: 20,
        totalSeats: 60,
      },
      {
        id: 303,
        time: '07:00 PM',
        format: '2D',
        language: 'Hindi',
        price: { silver: 170, gold: 260, platinum: 430 },
        availableSeats: 5,
        totalSeats: 90,
      },
    ],
  },
];

export const cities = [
  'Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Kolkata',
  'Hyderabad', 'Pune', 'Ahmedabad', 'Jaipur', 'Surat',
];
